version: '3'

services:

  proxy:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ../ops/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - demo
    depends_on:
      - app

  app:
    image: thedaveops/app
    build:
      context: .
    command: sh -c 'sleep 10; npm start'
    env_file:
      - ./env
    networks:
      - demo
    depends_on:
      - db

  db:
    image: mysql/mysql-server
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD="cambiamePorfavor!"
    volumes:
      - ../ops:/docker-entrypoint-initdb.d
    networks:
      - demo

networks:
  demo:
