---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ack-demo
  region: us-east-1
  version: '1.29'

vpc:
  id: "vpc-0de6dcebcb1d1e89e"
  clusterEndpoints:
    publicAccess:  true
  subnets:
    public:
      public-1-us-east-1a:
        id: "subnet-060ff58f504f124dd"
      public-2-us-east-1b:
        id: "subnet-0f178e1e24a05cbba"
      public-3-us-east-1c:
        id: "subnet-0b95cc7f6b3fdc0b7"

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3.small
    privateNetworking: false
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 30
    labels: {node-group-type: managed}
    tags:
      nodegroup-role: worker




